sudo: false
dist: bionic

services:
  - docker

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - python3
      - python3-pip
      - pkg-config
      - libboost-all-dev
      - libeigen3-dev
      - googletest

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - cd domains/integrator_chains && docker build -t fmr:integrator_chains . && cd ../..
  - mkdir results
  - docker network create x
  - docker run -d -it --rm --net=x --name icmain -h icmain -v examples/sci_concrete_examples/trialconf:/root/trialconf:Z,ro -v ./results:/root/results:Z,rw fmr:integrator_chains bash -c "cd integrators_workspace && source install/setup.bash && python /root/trial-runner.py -l -F /root/results/mydata.json /root/trialconf/mc-small-out3-order3.json"
  - sleep 5 && docker run --net=x -e="ROS_MASTER_URI=http://icmain:11311" --name smoketest -h smoketest -it --rm fmr:integrator_chains bash -c "cd integrators_workspace && source install/setup.bash && rostopic list && rostopic info /dynamaestro/loutput"
  - docker stop icmain

install:
  - ./ci/ubuntu-build-gtest.sh
  - pip3 install -U pip && pip3 install setuptools
  - cd tools/fmrb-pkg && pip3 install -r requirements.txt && pip3 install . && cd ../..

script:
  - cd domains/integrator_chains/dynamaestro
  - mkdir build && cd build && cmake .. && make
  - ctest -V

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
