sudo: false
dist: bionic
addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - python3
      - python3-pip
      - pkg-config
      - libboost-all-dev
      - libeigen3-dev
      - googletest

language: cpp
compiler:
  - gcc

install:
  - ./ci/ubuntu-build-gtest.sh
  - pip3 install -U pip && pip3 install setuptools
  - cd tools/fmrb-pkg && pip3 install -r requirements.txt && pip3 install . && cd ../..

script:
  - cd domains/integrator_chains/dynamaestro
  - mkdir build && cd build && cmake .. && make
  - ctest -V

notifications:
  email: false