# Emacs, this is in -*- ruby -*-
#
# The directory one level up from this file is synced with /vagrant in the VM.
# The intended usage is
#
#   cd /your/path/to/fmrbenchmark/remote
#   vagrant up
#   vagrant ssh
#   cd /vagrant
#
# This Vagrantfile is based on that of TuLiP <tulip-control.org>.


install_dependencies = <<-SHELL
#!/bin/sh -e
sudo apt-get -y update
sudo apt-get -y install python-pip python-nose
sudo apt-get -y install python-numpy python-scipy python-matplotlib
sudo apt-get -y install cython libgmp-dev
sudo pip install pycddlib
sudo apt-get -y install gfortran liblapack-dev
sudo pip install slycot
sudo pip install control

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver pgp.mit.edu --recv-key 0xB01FA116
sudo apt-get -y update
sudo apt-get -y install ros-indigo-ros-base python-rosinstall
sudo apt-get -y install ros-indigo-kobuki-node ros-indigo-kobuki-description ros-indigo-kobuki-gazebo

sudo rosdep init
rosdep update
echo 'source /opt/ros/indigo/setup.bash' >> ~vagrant/.bashrc
SHELL

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: install_dependencies
  config.vm.synced_folder "..", "/vagrant"
end
